### ISSUE TITLE
how to do it over wan

### ISSUE THREAD

**Issue by rasiras** [sempervictus/xssf#3]

**Comment by sempervictus** [comment]
This thing needs an overhaul, probably a full conversion to beef. Wan works same as LAN, need to take Nat into account though. Would also caution that this should only be done with explicit permission from the targets owner. Sorry for the disclaimer, but the community often gets inquiries from people seeking to do harm with the tools we make.

**Comment by rasiras** [comment]
Now it show error cannot bind to port 80 what to do

**Comment by sempervictus** [comment]
You either have another bind on the port or lack privilege to bind low ports (can run your ruby binary as root or grant the cap to your uid).
